server:
  port: 50102
eureka:
  client:
    fetch-registry: true # 单机关闭
    register-with-eureka: true # 单机关闭
    service-url:
      defaultZone: http://eureka01:50101/eureka/
  instance:
    hostname: eureka02