server:
  port: 31400
spring:
  application:
    name: xc-service-manage-media
  data:
    mongodb:
      uri:  mongodb://root:root@localhost:27017
      database: xc_media
xc-service-manage-media:
  upload-location: D:/Github/xcEdu/xcEduVideos/
  mq:
      routingkey-media-video: routingkey_media_video

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:50101/eureka/,http://localhost:50102/eureka/
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#    ip-address: 127.0.0.1
#ribbon:
#  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
#  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
#  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
#  ConnectTimeout: 5000  #请求连接的超时时间
#  ReadTimeout: 6000 #请求处理的超时时间